### ISSUE TITLE
activate the body

### ISSUE THREAD

**Issue by genekogan** [brahman-ai/mars-rover#3]
let rover rove.
 - [reprogramming hoverboards for robots](https://hackaday.io/project/158256-hoverbot/log/146067-reprogramming-hoverboards-for-robots)
 - [hoverboard firmware hack](https://github.com/NiklasFauth/hoverboard-firmware-hack)

**Comment by phillipdavidstearns** [comment]
[consider the body activated.](https://github.com/brahman-ai/mars-rover/blob/master/locomotion/WebApp/JetsonNano/images/rover-on-mars.jpg)
